# Generated by Django 3.1.1 on 2020-09-10 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pisteet', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tulokset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ottelupari', models.CharField(max_length=100)),
                ('tulos', models.CharField(blank=True, max_length=5)),
                ('pelattu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Veikkaukset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veikkaus', models.CharField(max_length=5)),
                ('osallistuja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futis.profile')),
                ('tulokset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futis.tulokset')),
            ],
        ),
    ]
