# Generated by Django 3.1 on 2020-08-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osallistujat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osallistuja', models.CharField(max_length=30, unique=True)),
                ('pisteet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tulokset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ottelupari', models.CharField(max_length=100)),
                ('tulos', models.CharField(default='', max_length=5)),
                ('pelattu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Veikkaukset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veikkaus', models.CharField(max_length=5)),
                ('osallistujat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futis.osallistujat')),
                ('tulokset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futis.tulokset')),
            ],
        ),
    ]
